stages:
  split:
    cmd: python ${split_config.prog_filepath}
    deps:
    - ${split_config.prog_filepath}
    - params.yaml
    - src/data/import_raw_data.py
    - https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv
    outs:
    - ${split_config.output_folderpath}/${split_config.X_train_filename}
    - ${split_config.output_folderpath}/${split_config.X_test_filename}
    - ${split_config.output_folderpath}/${split_config.y_train_filename}
    - ${split_config.output_folderpath}/${split_config.y_test_filename}

  normalize:
    cmd: python ${normalize_config.prog_filepath}
    deps:
    - ${normalize_config.prog_filepath}
    - params.yaml
    - ${split_config.output_folderpath}/${split_config.X_train_filename}
    - ${split_config.output_folderpath}/${split_config.X_test_filename}
    outs:
    - ${split_config.output_folderpath}/${split_config.X_train_scaled_filename}
    - ${split_config.output_folderpath}/${split_config.X_test_scaled_filename}

  gridSearch:
    cmd: python ${grid_search_config.prog_filepath}
    deps:
    - ${grid_search_config.prog_filepath}
    - params.yaml
    - ${split_config.output_folderpath}/${split_config.X_train_scaled_filename}
    - ${split_config.output_folderpath}/${split_config.y_train_filename}
    outs:
    - ${grid_search_config.best_params_filepath}

  training:
    cmd: python ${training_config.prog_filepath}
    deps:
    - ${training_config.prog_filepath}
    - params.yaml
    - ${grid_search_config.best_params_filepath}
    - ${split_config.output_folderpath}/${split_config.X_train_scaled_filename}
    - ${split_config.output_folderpath}/${split_config.y_train_filename}
    outs:
    - ${training_config.model_filepath}

  evaluate:
    cmd: python ${evaluate_config.prog_filepath}
    deps:
    - ${evaluate_config.prog_filepath}
    - params.yaml
    - ${grid_search_config.best_params_filepath}
    - ${training_config.model_filepath}
    - ${split_config.output_folderpath}/${split_config.X_test_scaled_filename}
    - ${split_config.output_folderpath}/${split_config.y_test_filename}
    outs:
    - ${evaluate_config.predictions_filepath}
    metrics:
    - ${evaluate_config.metrics_filepath}
