stages:
  split:
    cmd: python ${split_config.prog_filepath}
    deps:
    - https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv
    - src/data/import_raw_data.py
    - ${split_config.prog_filepath}
    - params.yaml
    outs:
    - ${split_config.output_folderpath}/${split_config.output_X_train_filename}
    - ${split_config.output_folderpath}/${split_config.output_X_test_filename}
    - ${split_config.output_folderpath}/${split_config.output_y_train_filename}
    - ${split_config.output_folderpath}/${split_config.output_y_test_filename}
